# Generated by Django 6.0.2 on 2026-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbookcheckout',
            name='book_uid_stored',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberbookcheckout',
            name='member_id_stored',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
